# Generated by Django 2.1.1 on 2018-11-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital_one_id', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('street_name', models.CharField(max_length=64)),
                ('street_number', models.IntegerField()),
                ('zip', models.IntegerField()),
                ('category', models.CharField(max_length=256)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=8)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=8)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
    ]
