# Generated by Django 2.1.1 on 2018-11-10 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IPInform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='zip',
            new_name='zip_code',
        ),
    ]
