# Generated by Django 2.1.1 on 2018-11-11 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IPInform', '0003_auto_20181111_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='fips_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fips_data', to='IPInform.FipsData'),
        ),
    ]
