# Generated by Django 2.1.1 on 2018-11-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPInform', '0003_auto_20181110_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='street_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
