# Generated by Django 2.1.1 on 2018-11-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPInform', '0004_auto_20181110_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
    ]
