# Generated by Django 2.1.1 on 2018-11-11 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IPInform', '0005_auto_20181111_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traffic',
            name='fips_data_id',
        ),
        migrations.AddField(
            model_name='traffic',
            name='fips_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fips_data', to='IPInform.FipsData'),
        ),
    ]
