# Generated by Django 2.1.1 on 2018-11-11 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IPInform', '0006_auto_20181111_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traffic',
            name='fips_data',
        ),
        migrations.DeleteModel(
            name='FipsData',
        ),
    ]
