# Generated by Django 2.1.1 on 2018-11-10 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IPInform', '0007_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='ip_address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='to_address', to='IPInform.IPAddress'),
            preserve_default=False,
        ),
    ]
