# Generated by Django 2.1.1 on 2018-11-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPInform', '0008_auto_20181110_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='ip',
            field=models.GenericIPAddressField(default=None),
            preserve_default=False,
        ),
    ]
