# Generated by Django 2.1.1 on 2018-11-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPInform', '0009_auto_20181110_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='ip',
            field=models.CharField(max_length=64),
        ),
    ]
