# Generated by Django 2.1.1 on 2018-11-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPInform', '0009_fipsdata_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='fipsdata',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True),
        ),
    ]
