# Generated by Django 2.1.1 on 2018-11-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPInform', '0010_fipsdata_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fipsdata',
            name='mean_income',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True),
        ),
    ]
