# Generated by Django 2.1.1 on 2018-11-10 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IPInform', '0011_auto_20181110_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traffic', to='IPInform.Merchant')),
            ],
        ),
    ]
