# Generated by Django 2.1.1 on 2018-11-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPInform', '0011_auto_20181111_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(blank=True, max_length=64, null=True)),
                ('company_domain', models.CharField(blank=True, max_length=256, null=True)),
                ('company_funding', models.IntegerField(blank=True, null=True)),
                ('company_keywords', models.CharField(blank=True, max_length=256, null=True)),
                ('company_mattermark_score', models.IntegerField(blank=True, null=True)),
                ('object_id', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
