# Generated by Django 2.1.1 on 2018-11-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPInform', '0012_traffic'),
    ]

    operations = [
        migrations.AddField(
            model_name='traffic',
            name='category',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='traffic',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
