# Generated by Django 2.1.1 on 2018-11-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPInform', '0013_businessinfo_fips'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='app_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='play_url',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='revenue_range',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
