# Generated by Django 2.1.1 on 2018-11-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPInform', '0013_auto_20181110_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
    ]
